default_platform :ios

platform :ios do
  before_all do
    # ipa scheme: 'Buildkite Fastlane Demo'

    # Instead of using the ipa action above we'll run it manually ourselves,
    # but not piped through xcpretty - so we can see what the output is
    sh 'cd .. && set -o pipefail && krausefx-ipa build -s "Buildkite Fastlane Demo" --verbose'
  end

  desc "Runs all the tests"
  lane :test do
    xctest scheme: 'Buildkite Fastlane Demo',
           sdk: 'iphonesimulator',
           destination: 'platform=iOS Simulator,name=iPhone 6,OS=9.0',
           derivedDataPath: './fastlane/xcodebuild-data'
  end
end
