opt_out_usage

fastlane_version "1.15.0"

default_platform :ios

platform :ios do
  before_all do
    ipa
  end

  desc "Runs all the tests"
  lane :test do
    xctest scheme: 'Buildkite Fastlane Demo', sdk: 'iphonesimulator'
  end
end
